name: Cuando hace push en feature/* con commit clave, corre las pruebas y mezcla con develop
on:
  push:
    branches:
      - "feature/*"

permissions:
  contents: write
  pull-requests: write
jobs:
  job-pruebas:
    name: Ejecutar pruebas automáticas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configuración de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas-automaticas-v1
        run: python -m unittest discover -s tests -v -p "test_*.py"

  job-merge-develop:
    name: Merge automático a develop
    runs-on: ubuntu-latest
    needs: job-pruebas
    if: contains(github.event.head_commit.message, '[FINISHED]')
    steps:
      - name: Merge directo a develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: develop
          commit-message: "Merge automático: ${{ github.ref_name }} → develop"