name: Verifica pruebas cuando se mezcla feature a develop
on:
  pull_request:
    branches:
      - develop
jobs:
  job-prueba-merge-develop:
    name: Ejecutar pruebas automáticas cuando se mezcla feature a develop (python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configuración de entorno de python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas-automaticas-v1
        run: python -m unittest discover -s test -v