name: Hola mundo
on:
  push:
    branches: [ develop ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo v2
      run: |
        echo $MI_VARIABLE.
    - name: cualquier nombre jobs
      run: echo "cualquier cosa"